#!/bin/bash

# Python-based fact extractor (replaces LLVM 3.8 opt pass).
# Generated by Claude Code to work with any modern clang version.

CLANG="${CLANG:-$(which clang)}"
EXTRACT_FACTS="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/extract_facts.py"

# Test Path
TEST_PATH=`pwd`

# Z3 path
Z3_BIN="${Z3:-$(which z3)}"

# Clang flags (suppress warnings from old benchmark code)
CFLAGS="-emit-llvm -S -O0 -Wno-implicit-function-declaration"

build_single() {
    echo "Build first version.."
    echo "$CLANG $CFLAGS -c main1.c"
    $CLANG $CFLAGS -c main1.c || die "error: clang"

    echo "python3 $EXTRACT_FACTS main1.ll 1"
    python3 "$EXTRACT_FACTS" main1.ll 1 || die "error: extract_facts"
    echo "main1.ll.facts.smt2 file is generated"

    echo "Build second version.."
    echo "$CLANG $CFLAGS -c main2.c"
    $CLANG $CFLAGS -c main2.c || die "error: clang"

    MATCH_ARGS=""
    [ -f statementMatch.txt ] && MATCH_ARGS="statementMatch.txt"
    [ -f lockMatch.txt ] && MATCH_ARGS="$MATCH_ARGS lockMatch.txt"

    echo "python3 $EXTRACT_FACTS main2.ll 2 $MATCH_ARGS"
    python3 "$EXTRACT_FACTS" main2.ll 2 $MATCH_ARGS || die "error: extract_facts"
    echo "main2.ll.facts.smt2 file is generated"
}

build_single_pp() {
    echo "Build first version.."
    echo "$CLANG $CFLAGS -c main1.cpp"
    $CLANG $CFLAGS -c main1.cpp || die "error: clang"

    echo "python3 $EXTRACT_FACTS main1.ll 1"
    python3 "$EXTRACT_FACTS" main1.ll 1 || die "error: extract_facts"
    echo "main1.ll.facts.smt2 file is generated"

    echo "Build second version.."
    echo "$CLANG $CFLAGS -c main2.cpp"
    $CLANG $CFLAGS -c main2.cpp || die "error: clang"

    MATCH_ARGS=""
    [ -f statementMatch.txt ] && MATCH_ARGS="statementMatch.txt"
    [ -f lockMatch.txt ] && MATCH_ARGS="$MATCH_ARGS lockMatch.txt"

    echo "python3 $EXTRACT_FACTS main2.ll 2 $MATCH_ARGS"
    python3 "$EXTRACT_FACTS" main2.ll 2 $MATCH_ARGS || die "error: extract_facts"
    echo "main2.ll.facts.smt2 file is generated"
}
