#!/usr/bin/env python3
"""
extract_facts.py - Python replacement for the LLVM DiffDep pass.

Parses LLVM IR (.ll) files and generates .facts.smt2 files containing
Datalog ground facts for the EC-Diff semantic diffing tool.

This script was generated by Claude Code to replace the original LLVM 3.8
pass-based approach, enabling the tool to work with any modern clang version.

Usage:
    python3 extract_facts.py <input.ll> <pNumber> [statementMatch.txt] [lockMatch.txt]

Arguments:
    input.ll           - LLVM IR file (produced by: clang -emit-llvm -S -c file.c -O0)
    pNumber            - Program number: 1 or 2
    statementMatch.txt - (Optional, P2 only) Statement ID remapping file
    lockMatch.txt      - (Optional, P2 only) Lock ID remapping file
"""

import sys
import re
import os


# ---------------------------------------------------------------------------
# ID generation helpers
# ---------------------------------------------------------------------------

def hex_id(n):
    """Regular instruction ID: #x0000 .. #xefff"""
    return "#x{:04x}".format(n)

def hex_id_lock(n):
    """Lock instruction ID: #xf000 .. #xffff"""
    s = format(n, 'x')
    return "#xf" + "0" * (3 - len(s)) + s


# ---------------------------------------------------------------------------
# IR name normalization
# ---------------------------------------------------------------------------

def normalize_call_target(name):
    """Normalize an IR call target to a canonical function name."""
    if name.startswith('"') and name.endswith('"'):
        name = name[1:-1]
    # macOS mangling: \01_pthread_join -> pthread_join
    if name.startswith('\\01'):
        name = name[3:]
        if name.startswith('_'):
            name = name[1:]
    return name


def extract_global_name(ref):
    """Extract the variable name from an @global reference."""
    if ref and ref.startswith('@'):
        name = ref[1:]
        # Strip quotes if present
        if name.startswith('"') and name.endswith('"'):
            name = name[1:-1]
        return name
    return None


# ---------------------------------------------------------------------------
# Data structures
# ---------------------------------------------------------------------------

class Instruction:
    def __init__(self, text):
        self.text = text.strip()
        self.result_var = None
        m = re.match(r'(%[\w.]+)\s*=', self.text)
        if m:
            self.result_var = m.group(1)

    @property
    def is_terminator(self):
        t = self.text
        return (t.startswith('br ') or t.startswith('ret ') or
                t == 'ret void' or t == 'unreachable' or
                t.startswith('switch ') or t.startswith('indirectbr '))

    @property
    def is_call(self):
        return 'call ' in self.text and '@' in self.text

    @property
    def is_store(self):
        return self.text.startswith('store ')

    @property
    def is_load(self):
        return 'load ' in self.text and '=' in self.text

    def get_call_target_raw(self):
        m = re.search(r'@("(?:[^"\\]|\\.)*"|[\w.]+)\s*\(', self.text)
        return m.group(1) if m else None

    def get_call_target(self):
        raw = self.get_call_target_raw()
        return normalize_call_target(raw) if raw else None

    def get_call_args_text(self):
        """Return the raw argument string from a call instruction."""
        raw_target = self.get_call_target_raw()
        if not raw_target:
            return ""
        # Escape for regex
        escaped = re.escape(raw_target)
        m = re.search(r'@' + escaped + r'\s*\((.+)\)', self.text)
        if not m:
            # Try without the result assignment prefix
            m = re.search(r'@' + escaped + r'\s*\((.+)\)\s*(?:#\d+)?$', self.text)
        return m.group(1) if m else ""

    def get_call_args(self):
        """Split call arguments by top-level commas."""
        args_str = self.get_call_args_text()
        if not args_str:
            return []
        args = []
        depth = 0
        current = ""
        for ch in args_str:
            if ch == '(':
                depth += 1
            elif ch == ')':
                depth -= 1
            elif ch == ',' and depth == 0:
                args.append(current.strip())
                current = ""
                continue
            current += ch
        if current.strip():
            args.append(current.strip())
        return args

    def get_call_arg_value(self, index):
        """Get the value token (last word) of a call argument."""
        args = self.get_call_args()
        if index < len(args):
            tokens = args[index].split()
            return tokens[-1] if tokens else None
        return None

    def get_store_pointer(self):
        """Extract the pointer operand from a store instruction."""
        parts = self.text.split(',')
        if len(parts) >= 2:
            ptr_part = parts[1].strip()
            # Look for @global or %local reference after 'ptr'
            m = re.search(r'(?:ptr\s+(?:noundef\s+)?)?(@"[^"]+"|@[\w.]+|%[\w.]+)', ptr_part)
            if m:
                return m.group(1)
        return None

    def get_load_pointer(self):
        """Extract the pointer operand from a load instruction."""
        parts = self.text.split(',')
        if len(parts) >= 2:
            ptr_part = parts[1].strip()
            m = re.search(r'(?:ptr\s+(?:noundef\s+)?)?(@"[^"]+"|@[\w.]+|%[\w.]+)', ptr_part)
            if m:
                return m.group(1)
        return None

    def get_successor_labels(self):
        """Extract successor basic block labels from a terminator."""
        labels = []
        t = self.text
        if t.startswith('br i1'):
            for m in re.finditer(r'label\s+%([\w.]+)', t):
                labels.append(m.group(1))
        elif t.startswith('br label'):
            m = re.search(r'label\s+%([\w.]+)', t)
            if m:
                labels.append(m.group(1))
        elif t.startswith('switch'):
            for m in re.finditer(r'label\s+%([\w.]+)', t):
                labels.append(m.group(1))
        return labels


class BasicBlock:
    def __init__(self, label):
        self.label = label
        self.instructions = []
        self.succs = []   # BasicBlock refs
        self.preds = []   # BasicBlock refs


class Function:
    def __init__(self, name):
        self.name = name
        self.blocks = []        # in order
        self.block_map = {}     # label -> BasicBlock

    def build_cfg(self):
        for bb in self.blocks:
            if bb.instructions and bb.instructions[-1].is_terminator:
                for sl in bb.instructions[-1].get_successor_labels():
                    if sl in self.block_map:
                        succ = self.block_map[sl]
                        if succ not in bb.succs:
                            bb.succs.append(succ)
                        if bb not in succ.preds:
                            succ.preds.append(bb)


class Module:
    def __init__(self):
        self.functions = []     # Function objects in definition order
        self.func_map = {}


# ---------------------------------------------------------------------------
# LLVM IR parser
# ---------------------------------------------------------------------------

def parse_ll(filename):
    with open(filename) as f:
        lines = f.readlines()

    module = Module()
    i = 0
    while i < len(lines):
        line = lines[i]

        # Match function definition
        m = re.match(r'^define\s+.*?@([\w.]+)\s*\(', line)
        if m:
            func_name = m.group(1)
            func = Function(func_name)

            # Skip to opening brace (usually on the same line)
            while i < len(lines) and '{' not in lines[i]:
                i += 1
            i += 1  # move past the { line

            current_bb = BasicBlock("entry")

            while i < len(lines):
                bline = lines[i]
                stripped = bline.strip()

                if stripped == '}':
                    break

                if not stripped or stripped.startswith(';'):
                    i += 1
                    continue

                # Label: starts at column 0 (not indented) and contains ':'
                if bline[0:1] != ' ' and bline[0:1] != '\t' and ':' in bline:
                    label_text = bline.split(':')[0].strip()
                    # Verify it looks like a label (not a global def)
                    if re.match(r'^[\w.]+$', label_text):
                        if current_bb.instructions:
                            func.blocks.append(current_bb)
                            func.block_map[current_bb.label] = current_bb
                        current_bb = BasicBlock(label_text)
                        i += 1
                        continue

                inst = Instruction(stripped)
                current_bb.instructions.append(inst)
                i += 1

            # Save last block
            if current_bb.instructions:
                func.blocks.append(current_bb)
                func.block_map[current_bb.label] = current_bb

            func.build_cfg()
            module.functions.append(func)
            module.func_map[func_name] = func

        i += 1

    return module


# ---------------------------------------------------------------------------
# Dominator / Post-Dominator tree computation
# ---------------------------------------------------------------------------

def compute_dom_children(blocks, entry):
    """Compute dominator tree children using iterative dataflow."""
    if not blocks:
        return {}

    all_set = set(blocks)
    dom = {}
    for b in blocks:
        dom[b] = frozenset({b}) if b is entry else frozenset(all_set)

    changed = True
    while changed:
        changed = False
        for b in blocks:
            if b is entry or not b.preds:
                continue
            pred_doms = [dom[p] for p in b.preds if p in dom]
            if not pred_doms:
                continue
            new_dom = frozenset(set.intersection(*[set(d) for d in pred_doms]) | {b})
            if new_dom != dom[b]:
                dom[b] = new_dom
                changed = True

    # Immediate dominators -> children map
    children = {b: [] for b in blocks}
    for b in blocks:
        if b is entry:
            continue
        strict = set(dom[b]) - {b}
        if not strict:
            continue
        idom = max(strict, key=lambda x: len(dom[x]))
        children[idom].append(b)

    return children


def compute_postdom_children(blocks):
    """Compute post-dominator tree children using reversed CFG."""
    if not blocks:
        return {}

    exit_blocks = [b for b in blocks if not b.succs]
    if not exit_blocks:
        return {b: [] for b in blocks}

    # Sentinel for virtual exit
    VIRTUAL_EXIT = "___virtual_exit___"
    all_nodes = list(blocks) + [VIRTUAL_EXIT]
    all_set = set(all_nodes)

    # Reversed CFG predecessors.
    # Original edge A→B becomes reversed edge B→A.
    # Predecessors of X in reversed CFG = successors of X in original CFG.
    # Additionally, virtual_exit has edges TO each exit block, so exit blocks
    # have virtual_exit as a predecessor in the reversed CFG.
    exit_set = set(exit_blocks)

    def rev_preds(node):
        if node is VIRTUAL_EXIT:
            return []  # root of reversed CFG has no predecessors
        result = list(node.succs)  # successors in original = predecessors in reversed
        if node in exit_set:
            result.append(VIRTUAL_EXIT)
        return result

    dom = {}
    for n in all_nodes:
        dom[n] = frozenset({n}) if n is VIRTUAL_EXIT else frozenset(all_set)

    changed = True
    while changed:
        changed = False
        for n in all_nodes:
            if n is VIRTUAL_EXIT:
                continue
            preds = rev_preds(n)
            if not preds:
                continue
            pred_doms = [dom[p] for p in preds if p in dom]
            if not pred_doms:
                continue
            new_dom = frozenset(set.intersection(*[set(d) for d in pred_doms]) | {n})
            if new_dom != dom[n]:
                dom[n] = new_dom
                changed = True

    # Build children (only real blocks)
    children = {b: [] for b in blocks}
    for b in blocks:
        strict = set(dom[b]) - {b}
        real_strict = [d for d in strict if d is not VIRTUAL_EXIT]
        if not real_strict:
            continue
        ipdom = max(real_strict, key=lambda x: len(dom[x]))
        children[ipdom].append(b)

    return children


# ---------------------------------------------------------------------------
# Match file loader
# ---------------------------------------------------------------------------

def load_match_file(filename):
    """Load a statementMatch.txt or lockMatch.txt file.

    Format per line: p1ID:p2ID
    Returns dict mapping p2ID -> p1ID (for remapping P2 IDs to P1 equivalents).
    """
    result = {}
    if not filename or not os.path.exists(filename):
        return result
    with open(filename) as f:
        for line in f:
            line = line.strip()
            if not line or ':' not in line:
                continue
            p1_id, p2_id = line.split(':', 1)
            p1_id = p1_id.strip()
            p2_id = p2_id.strip()
            if p1_id and p2_id:
                result[p2_id] = p1_id
    return result


# ---------------------------------------------------------------------------
# Fact extractor
# ---------------------------------------------------------------------------

class FactExtractor:
    """Extracts Datalog ground facts from a parsed LLVM IR module.

    Replicates the behavior of the original C++ DiffDep LLVM pass,
    including ID assignment order and output format.
    """

    LOCK_CALL_TARGETS = frozenset([
        'pthread_mutex_lock', 'pthread_mutex_unlock',
        'pthread_join', 'pthread_cond_wait', 'pthread_cond_signal',
        'nop1',
    ])

    def __init__(self, module, p_number, st_num_map=None, lock_num_map=None):
        self.module = module
        self.p_number = p_number
        self.p_bit = "#b0" if p_number == 1 else "#b1"

        self.st_num_map = st_num_map or {}
        self.lock_num_map = lock_num_map or {}

        # Counters
        self.inst_counter = 0
        self.lock_inst_counter = 0
        self.thread_counter = 0
        self.lock_var_counter = 0
        self.shared_var_counter = 0

        # ID maps  —  keyed by (func_name, bb_label, inst_index)
        self.inst_id = {}
        self.lock_inst_id = {}

        # Thread bookkeeping
        self.thread_map = {}        # name -> hex_id
        self.thread_map_rev = {}    # hex_id -> name
        self.thread_tid_map = {}    # alloca ref (e.g. "%2") -> thread func name

        # Lock & shared variable maps
        self.lock_var_map = {}      # global name -> hex_id
        self.shared_var_map = {}    # global name -> hex_id

        # Per-function load maps for pthread_join tid tracing
        self.load_maps = {}         # func_name -> {result_var -> source_ptr}

        # Fact accumulation strings (order matches original output)
        self.f_thread_create = []
        self.f_thread_join = []
        self.f_thread_cond = []     # threadCondWait + threadCondSignal
        self.f_st = []
        self.f_impo = []
        self.f_lock = []
        self.f_nolock = []
        self.f_read = []            # read + busyRead + busyWrite
        self.f_write = []
        self.f_dom = []
        self.f_postdom = []

    # -- ID assignment (on-demand, matching original traversal order) -------

    def _get_id(self, func_name, bb_label, idx):
        key = (func_name, bb_label, idx)
        if key in self.lock_inst_id:
            return self.lock_inst_id[key]
        if key in self.inst_id:
            return self.inst_id[key]
        new_id = hex_id(self.inst_counter)
        self.inst_counter += 1
        if self.p_number == 2 and new_id in self.st_num_map:
            new_id = self.st_num_map[new_id]
        self.inst_id[key] = new_id
        return new_id

    def _register_lock_inst(self, func_name, bb_label, idx):
        key = (func_name, bb_label, idx)
        new_id = hex_id_lock(self.lock_inst_counter)
        self.lock_inst_counter += 1
        if self.p_number == 2 and new_id in self.st_num_map:
            new_id = self.st_num_map[new_id]
        self.lock_inst_id[key] = new_id

    def _get_thread_id(self, name):
        if name in self.thread_map:
            return self.thread_map[name]
        tid = hex_id(self.thread_counter)
        self.thread_counter += 1
        self.thread_map[name] = tid
        self.thread_map_rev[tid] = name
        return tid

    def _get_lock_var_id(self, name):
        if name in self.lock_var_map:
            return self.lock_var_map[name]
        new_id = hex_id(self.lock_var_counter)
        self.lock_var_counter += 1
        if self.p_number == 2 and new_id in self.lock_num_map:
            new_id = self.lock_num_map[new_id]
        self.lock_var_map[name] = new_id
        return new_id

    def _get_shared_id(self, name):
        if name in self.shared_var_map:
            return self.shared_var_map[name]
        new_id = hex_id(self.shared_var_counter)
        self.shared_var_counter += 1
        self.shared_var_map[name] = new_id
        return new_id

    # -- Phase 1: find threads ----------------------------------------------

    def find_threads(self):
        self._get_thread_id("main")
        for func in self.module.functions:
            for bb in func.blocks:
                for inst in bb.instructions:
                    if not inst.is_call:
                        continue
                    target = inst.get_call_target()
                    if target != "pthread_create":
                        continue
                    # 3rd arg (index 2) = thread function
                    func_val = inst.get_call_arg_value(2)
                    gname = extract_global_name(func_val)
                    if gname:
                        self._get_thread_id(gname)
                        # 1st arg (index 0) = tid alloca pointer
                        tid_val = inst.get_call_arg_value(0)
                        if tid_val:
                            self.thread_tid_map[tid_val] = gname

    # -- Phase 2: find & pre-register lock instructions ---------------------

    def find_locks(self):
        for func in self.module.functions:
            for bb in func.blocks:
                for idx, inst in enumerate(bb.instructions):
                    if not inst.is_call:
                        continue
                    target = inst.get_call_target()
                    if target not in self.LOCK_CALL_TARGETS:
                        continue
                    self._register_lock_inst(func.name, bb.label, idx)
                    if target in ('pthread_mutex_lock', 'pthread_mutex_unlock'):
                        lock_val = inst.get_call_arg_value(0)
                        gname = extract_global_name(lock_val)
                        if gname:
                            self._get_lock_var_id(gname)

    # -- Phase 3: build load maps for join tracking -------------------------

    def _build_load_maps(self):
        for func in self.module.functions:
            lm = {}
            for bb in func.blocks:
                for inst in bb.instructions:
                    if inst.is_load and inst.result_var:
                        ptr = inst.get_load_pointer()
                        if ptr:
                            lm[inst.result_var] = ptr
            self.load_maps[func.name] = lm

    # -- Phase 4: main fact generation pass ---------------------------------

    def generate_facts(self):
        self._build_load_maps()

        for func in self.module.functions:
            if func.name == "nop1":
                continue
            if not func.blocks:
                continue

            thread_id = "#x0000"
            if func.name in self.thread_map:
                thread_id = self.thread_map[func.name]

            # Process each basic block's instructions
            for bb in func.blocks:
                self._process_bb(func, bb, thread_id)

            # Inter-BB program order
            for bb in func.blocks:
                self._inter_bb_po(func, bb)

            # Dominator / Post-dominator inter-BB facts
            self._dom_postdom(func)

    def _process_bb(self, func, bb, thread_id):
        p = self.p_bit
        for idx, inst in enumerate(bb.instructions):
            iid = self._get_id(func.name, bb.label, idx)

            # st fact
            self.f_st.append(f"(rule (st {iid} {thread_id} {p}))")

            # Intra-BB program order + dom + postDom
            if idx + 1 < len(bb.instructions):
                nid = self._get_id(func.name, bb.label, idx + 1)
                self.f_impo.append(f"(rule (impo {iid} {nid} {p}))")
                self.f_dom.append(f"(rule (dom {iid} {nid} {p}))")
                self.f_postdom.append(f"(rule (postDom {nid} {iid} {p}))")

            # Categorize
            if inst.is_call:
                self._handle_call(func, inst, iid, thread_id)
            elif inst.is_store:
                self._handle_store(func, inst, iid)
            elif inst.is_load:
                self._handle_load(func, inst, iid)
            else:
                self.f_nolock.append(f"(rule (nonLock {iid} {p}))")

    def _handle_call(self, func, inst, iid, thread_id):
        p = self.p_bit
        target = inst.get_call_target()

        if target == 'pthread_mutex_lock':
            gname = extract_global_name(inst.get_call_arg_value(0))
            if gname and gname in self.lock_var_map:
                lid = self.lock_var_map[gname]
                self.f_lock.append(f"(rule (lockAcquire {iid} {lid} {p}))")
            # No nonLock for lock/unlock

        elif target == 'pthread_mutex_unlock':
            gname = extract_global_name(inst.get_call_arg_value(0))
            if gname and gname in self.lock_var_map:
                lid = self.lock_var_map[gname]
                self.f_lock.append(f"(rule (lockRelease {iid} {lid} {p}))")

        elif target == 'pthread_create':
            gname = extract_global_name(inst.get_call_arg_value(2))
            if gname:
                tid = self._get_thread_id(gname)
                self.f_thread_create.append(
                    f"(rule (threadCreate {tid} {iid} {thread_id} {p}))")
            self.f_nolock.append(f"(rule (nonLock {iid} {p}))")

        elif target == 'pthread_join':
            join_val = inst.get_call_arg_value(0)
            lm = self.load_maps.get(func.name, {})
            if join_val and join_val in lm:
                tid_ptr = lm[join_val]
                if tid_ptr in self.thread_tid_map:
                    tname = self.thread_tid_map[tid_ptr]
                    tid = self._get_thread_id(tname)
                    self.f_thread_join.append(
                        f"(rule (threadJoin {tid} {iid} {thread_id} {p}))")
            self.f_nolock.append(f"(rule (nonLock {iid} {p}))")

        elif target == 'pthread_cond_wait':
            cond_name = extract_global_name(inst.get_call_arg_value(0))
            lock_name = extract_global_name(inst.get_call_arg_value(1))
            if cond_name and lock_name and lock_name in self.lock_var_map:
                sid = self._get_shared_id(cond_name)
                lid = self.lock_var_map[lock_name]
                self.f_thread_cond.append(
                    f"(rule (threadCondWait {sid} {lid} {iid} {p}))")
            self.f_nolock.append(f"(rule (nonLock {iid} {p}))")

        elif target == 'pthread_cond_signal':
            cond_name = extract_global_name(inst.get_call_arg_value(0))
            if cond_name:
                sid = self._get_shared_id(cond_name)
                # Original code stores signal facts in the condWait buffer
                self.f_thread_cond.append(
                    f"(rule (threadCondSignal {sid} {iid} {p}))")
            self.f_nolock.append(f"(rule (nonLock {iid} {p}))")

        else:
            self.f_nolock.append(f"(rule (nonLock {iid} {p}))")

    def _handle_store(self, func, inst, iid):
        p = self.p_bit
        ptr = inst.get_store_pointer()
        gname = extract_global_name(ptr)
        if gname:
            if "SHARED" in gname:
                sid = self._get_shared_id(gname)
                self.f_write.append(f"(rule (write {iid} {sid} {p}))")
            if "BUSY" in gname and func.name in self.thread_map:
                sid = self._get_shared_id(gname)
                # Original code stores busyWrite in readFacts
                self.f_read.append(f"(rule (busyWrite {iid} {sid} {p}))")
        self.f_nolock.append(f"(rule (nonLock {iid} {p}))")

    def _handle_load(self, func, inst, iid):
        p = self.p_bit
        ptr = inst.get_load_pointer()
        gname = extract_global_name(ptr)
        if gname:
            if "SHARED" in gname:
                sid = self._get_shared_id(gname)
                self.f_read.append(f"(rule (read {iid} {sid} {p}))")
            if "BUSY" in gname and func.name in self.thread_map:
                sid = self._get_shared_id(gname)
                self.f_read.append(f"(rule (busyRead {iid} {sid} {p}))")
        self.f_nolock.append(f"(rule (nonLock {iid} {p}))")

    def _inter_bb_po(self, func, bb):
        if not bb.instructions:
            return
        p = self.p_bit
        term_id = self._get_id(func.name, bb.label, len(bb.instructions) - 1)
        for succ in bb.succs:
            if succ.instructions:
                sid = self._get_id(func.name, succ.label, 0)
                self.f_impo.append(f"(rule (impo {term_id} {sid} {p}))")

    def _dom_postdom(self, func):
        if not func.blocks:
            return
        p = self.p_bit
        entry = func.blocks[0]

        dom_ch = compute_dom_children(func.blocks, entry)
        pdom_ch = compute_postdom_children(func.blocks)

        for b in func.blocks:
            for c in dom_ch.get(b, []):
                tid = self._get_id(func.name, b.label, len(b.instructions) - 1)
                fid = self._get_id(func.name, c.label, 0)
                self.f_dom.append(f"(rule (dom {tid} {fid} {p}))")

        for b in func.blocks:
            for c in pdom_ch.get(b, []):
                fid = self._get_id(func.name, b.label, 0)
                tid = self._get_id(func.name, c.label, len(c.instructions) - 1)
                self.f_postdom.append(f"(rule (postDom {fid} {tid} {p}))")

    # -- Output -------------------------------------------------------------

    def get_output(self):
        """Return all facts in the original output order."""
        sections = [
            self.f_thread_create,
            self.f_thread_join,
            self.f_thread_cond,
            self.f_st,
            self.f_impo,
            self.f_lock,
            self.f_nolock,
            self.f_read,
            self.f_write,
            self.f_dom,
            self.f_postdom,
        ]
        lines = []
        for section in sections:
            lines.extend(section)
        return "\n".join(lines) + "\n" if lines else ""

    def dump_thread_map(self, filename):
        with open(filename, 'w') as f:
            for name, tid in self.thread_map.items():
                f.write(f"{name}:{tid}\n")

    def dump_inst_map(self, filename):
        with open(filename, 'w') as f:
            for key, iid in sorted(self.inst_id.items(), key=lambda x: x[1]):
                f.write(f"{iid}:{key[0]}:{key[1]}:inst{key[2]}\n")
            for key, iid in sorted(self.lock_inst_id.items(), key=lambda x: x[1]):
                f.write(f"{iid}:{key[0]}:{key[1]}:inst{key[2]}\n")

    def dump_lock_map(self, filename):
        with open(filename, 'w') as f:
            for name, lid in self.lock_var_map.items():
                f.write(f"{name}:{lid}\n")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    if len(sys.argv) < 3:
        print("Usage: python3 extract_facts.py <input.ll> <pNumber>"
              " [statementMatch.txt] [lockMatch.txt]")
        sys.exit(1)

    ll_file = sys.argv[1]
    p_number = int(sys.argv[2])

    if p_number not in (1, 2):
        print("pNumber must be 1 or 2")
        sys.exit(1)

    st_match_file = sys.argv[3] if len(sys.argv) > 3 else None
    lock_match_file = sys.argv[4] if len(sys.argv) > 4 else None

    st_num_map = {}
    lock_num_map = {}
    if p_number == 2:
        st_num_map = load_match_file(st_match_file)
        lock_num_map = load_match_file(lock_match_file)

    # Parse
    module = parse_ll(ll_file)

    # Extract facts
    ext = FactExtractor(module, p_number, st_num_map, lock_num_map)
    ext.find_threads()
    ext.find_locks()
    ext.generate_facts()

    # Write output
    output_path = ll_file + ".facts.smt2"
    with open(output_path, 'w') as f:
        f.write(ext.get_output())
    print(f"Generated {output_path}")

    # Debug dumps
    base = ll_file
    ext.dump_thread_map(base + ".threadMap.txt")
    ext.dump_inst_map(base + ".instMap.txt")
    ext.dump_lock_map(base + ".lockMap.txt")


if __name__ == "__main__":
    main()
