#!/bin/bash
# Generate .ll and .facts.smt2 files for all benchmarks.
# Also assembles the full SMT2 query files (rules + facts + queries).
#
# This script was generated by Claude Code as a replacement for the
# original LLVM 3.8 pass-based build pipeline.
#
# Usage: ./generate_all.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
EXTRACT_FACTS="${SCRIPT_DIR}/extract_facts.py"
TEST_PATH="${SCRIPT_DIR}/test"
CLANG="${CLANG:-$(which clang)}"

source "${TEST_PATH}/testDir-small.sh"
SMALL_DIRS="$TESTDIRS"
source "${TEST_PATH}/testDir-large.sh" 2>/dev/null || true
LARGE_DIRS="${TESTDIRS:-}"

ALL_DIRS="$SMALL_DIRS $LARGE_DIRS"

PASS=0
FAIL=0

for d in ${ALL_DIRS}; do
    DIR="${TEST_PATH}/benchmarks/${d}"
    if [ ! -d "$DIR" ]; then
        continue
    fi

    cd "$DIR"
    echo -n "Processing $d ... "

    # Compile to LLVM IR
    # -Wno-implicit-function-declaration needed for some benchmarks
    # that call nop1() without a forward declaration
    CFLAGS="-emit-llvm -S -O0 -Wno-implicit-function-declaration"
    if ! $CLANG $CFLAGS -c main1.c 2>/dev/null; then
        echo "SKIP (clang failed on main1.c)"
        FAIL=$((FAIL + 1))
        continue
    fi
    if ! $CLANG $CFLAGS -c main2.c 2>/dev/null; then
        echo "SKIP (clang failed on main2.c)"
        FAIL=$((FAIL + 1))
        continue
    fi

    # Extract facts for P1
    python3 "$EXTRACT_FACTS" main1.ll 1 2>/dev/null

    # Extract facts for P2 (with optional match files)
    MATCH_ARGS=""
    [ -f statementMatch.txt ] && MATCH_ARGS="statementMatch.txt"
    [ -f lockMatch.txt ] && MATCH_ARGS="$MATCH_ARGS lockMatch.txt"
    python3 "$EXTRACT_FACTS" main2.ll 2 $MATCH_ARGS 2>/dev/null

    # Assemble full SMT2 query files for ranks 1, 2, 3
    for RANK in 1 2 3; do
        RANK_FILE="${TEST_PATH}/rank${RANK}_rules.smt2"
        [ ! -f "$RANK_FILE" ] && continue

        for q in check p1-p2 p2-p1; do
            QFILE="${TEST_PATH}/queries/${q}.smt2"
            [ -f "${TEST_PATH}/queries/${q}-rank${RANK}.smt2" ] && QFILE="${TEST_PATH}/queries/${q}-rank${RANK}.smt2"

            OUT="${q}-rank${RANK}-after.smt2"
            cat "${TEST_PATH}/general_rules-after.smt2" \
                "$RANK_FILE" \
                main1.ll.facts.smt2 \
                main2.ll.facts.smt2 \
                "$QFILE" > "$OUT"
        done
    done

    # MayHB queries
    for pq in mayHbP1 mayHbP2; do
        QFILE="${TEST_PATH}/queries/${pq}.smt2"
        if [ -f "$QFILE" ]; then
            OUT="${pq}-after.smt2"
            cat "${TEST_PATH}/general_rules-after.smt2" \
                main1.ll.facts.smt2 \
                main2.ll.facts.smt2 \
                "$QFILE" > "$OUT"
        fi
    done

    echo "OK"
    PASS=$((PASS + 1))
    cd "$SCRIPT_DIR"
done

echo ""
echo "Done: $PASS succeeded, $FAIL failed"
