#!/usr/bin/env python3
"""
smt2_to_souffle.py - Convert Z3 Datalog .smt2 files to Souffle .dl files.

Translates the EC-Diff SMT2 queries (which use Z3's fixedpoint Datalog engine)
into equivalent Souffle Datalog programs.

Generated by Claude Code.

Usage:
    python3 smt2_to_souffle.py <input.smt2> [output.dl]

If output is not specified, prints to stdout.
"""

import sys
import re
import os


# ---------------------------------------------------------------------------
# S-expression parser
# ---------------------------------------------------------------------------

def tokenize(text):
    tokens = []
    i = 0
    while i < len(text):
        c = text[i]
        if c in '()':
            tokens.append(c)
            i += 1
        elif c in ' \t\n\r':
            i += 1
        elif c == ';':
            while i < len(text) and text[i] != '\n':
                i += 1
        elif c == '"':
            j = i + 1
            while j < len(text) and text[j] != '"':
                if text[j] == '\\':
                    j += 1
                j += 1
            tokens.append(text[i:j+1])
            i = j + 1
        elif c == ':':
            # keyword like :print-answer
            j = i + 1
            while j < len(text) and text[j] not in '() \t\n\r;':
                j += 1
            tokens.append(text[i:j])
            i = j
        else:
            j = i
            while j < len(text) and text[j] not in '() \t\n\r;':
                j += 1
            tokens.append(text[i:j])
            i = j
    return tokens


def parse_sexpr(tokens, pos):
    if pos >= len(tokens):
        return None, pos
    if tokens[pos] == '(':
        lst = []
        pos += 1
        while pos < len(tokens) and tokens[pos] != ')':
            elem, pos = parse_sexpr(tokens, pos)
            lst.append(elem)
        return lst, pos + 1  # skip ')'
    else:
        return tokens[pos], pos + 1


def parse_all(text):
    tokens = tokenize(text)
    exprs = []
    pos = 0
    while pos < len(tokens):
        expr, pos = parse_sexpr(tokens, pos)
        if expr is not None:
            exprs.append(expr)
    return exprs


# ---------------------------------------------------------------------------
# Value conversion
# ---------------------------------------------------------------------------

def convert_value(v):
    """Convert an SMT2 value to a Souffle unsigned integer literal."""
    if isinstance(v, str):
        if v.startswith('#x'):
            return str(int(v[2:], 16))
        elif v.startswith('#b'):
            return str(int(v[2:], 2))
        elif v == 'false':
            return '0'
        elif v == 'true':
            return '1'
        else:
            return v
    return str(v)


def is_variable(v):
    """Check if a value is a Datalog variable (not a literal)."""
    if not isinstance(v, str):
        return False
    if v.startswith('#') or v in ('true', 'false'):
        return False
    # Variables are things like s1, s2, th1, l1, p1, A, B, etc.
    return True


# ---------------------------------------------------------------------------
# Rule body conversion
# ---------------------------------------------------------------------------

def convert_atom(expr):
    """Convert an atomic formula (relation application) to Souffle string."""
    if isinstance(expr, str):
        return convert_value(expr)
    if not isinstance(expr, list) or len(expr) == 0:
        return str(expr)

    head = expr[0]

    if head == 'and':
        parts = []
        for sub in expr[1:]:
            parts.append(convert_atom(sub))
        return ', '.join(parts)

    elif head == 'not':
        inner = expr[1]
        if isinstance(inner, list) and inner[0] == '=':
            # (not (= a b)) -> a != b
            a = convert_value(inner[1])
            b = convert_value(inner[2])
            return f'{a} != {b}'
        else:
            return '!' + convert_atom(inner)

    elif head == '=':
        a = convert_value(expr[1])
        b = convert_value(expr[2])
        return f'{a} = {b}'

    elif head == 'or':
        # Return a special marker for or-expansion
        parts = [convert_atom(sub) for sub in expr[1:]]
        return ('__OR__', parts)

    else:
        # Relation application: (rel arg1 arg2 ...)
        rel_name = head
        args = ', '.join(convert_value(a) for a in expr[1:])
        return f'{rel_name}({args})'


def flatten_body(expr):
    """Convert a rule body, handling OR by returning list of alternative conjunctions.

    Returns a list of lists of strings. Each inner list is one conjunction (one rule).
    """
    if isinstance(expr, str):
        return [[convert_value(expr)]]

    if not isinstance(expr, list):
        return [[str(expr)]]

    head = expr[0]

    if head == 'and':
        # Start with one empty conjunction
        results = [[]]
        for sub in expr[1:]:
            converted = convert_atom(sub)
            if isinstance(converted, tuple) and converted[0] == '__OR__':
                # Expand: each existing conjunction × each OR alternative
                new_results = []
                for existing in results:
                    for alt in converted[1]:
                        new_results.append(existing + [alt])
                results = new_results
            else:
                for conj in results:
                    conj.append(converted)
        return results

    elif head == 'or':
        # Top-level OR: each alternative becomes a separate rule
        results = []
        for sub in expr[1:]:
            sub_results = flatten_body(sub)
            results.extend(sub_results)
        return results

    elif head == 'not':
        inner = expr[1]
        if isinstance(inner, list) and inner[0] == '=':
            a = convert_value(inner[1])
            b = convert_value(inner[2])
            return [[f'{a} != {b}']]
        else:
            return [['!' + convert_atom(inner)]]

    elif head == '=':
        a = convert_value(expr[1])
        b = convert_value(expr[2])
        return [[f'{a} = {b}']]

    else:
        # Relation application
        rel_name = head
        args = ', '.join(convert_value(a) for a in expr[1:])
        return [[f'{rel_name}({args})']]


def convert_head(expr):
    """Convert a rule head to Souffle string."""
    if isinstance(expr, list):
        rel_name = expr[0]
        args = ', '.join(convert_value(a) for a in expr[1:])
        return f'{rel_name}({args})'
    return convert_value(expr)


# ---------------------------------------------------------------------------
# Main converter
# ---------------------------------------------------------------------------

class SMT2ToSouffle:
    def __init__(self):
        self.type_sorts = {}        # sort name -> base type
        self.relations = {}         # rel name -> list of sort names
        self.variables = {}         # var name -> sort name
        self.rules = []             # list of Souffle rule strings
        self.outputs = []           # list of relation names to output

    def process(self, exprs):
        for expr in exprs:
            if not isinstance(expr, list) or len(expr) == 0:
                continue
            cmd = expr[0]

            if cmd == 'set-option':
                pass  # skip

            elif cmd == 'define-sort':
                name = expr[1]
                self.type_sorts[name] = 'unsigned'

            elif cmd == 'declare-rel':
                rel_name = expr[1]
                sort_list = expr[2] if isinstance(expr[2], list) else [expr[2]]
                self.relations[rel_name] = sort_list

            elif cmd == 'declare-var':
                var_name = expr[1]
                var_type = expr[2]
                self.variables[var_name] = var_type

            elif cmd == 'rule':
                self._process_rule(expr[1])

            elif cmd == 'query':
                rel_name = expr[1]
                self.outputs.append(rel_name)

    def _process_rule(self, rule_expr):
        if isinstance(rule_expr, list) and rule_expr[0] == '=>':
            # Implication: (=> body head)
            body_expr = rule_expr[1]
            head_expr = rule_expr[2]
            head_str = convert_head(head_expr)
            body_alts = flatten_body(body_expr)
            for body_parts in body_alts:
                body_str = ', '.join(body_parts)
                self.rules.append(f'{head_str} :- {body_str}.')
        else:
            # Ground fact
            fact_str = convert_head(rule_expr)
            self.rules.append(f'{fact_str}.')

    def generate(self):
        lines = []
        lines.append('// Souffle Datalog program converted from Z3 fixedpoint SMT2')
        lines.append('// Generated by smt2_to_souffle.py (Claude Code)')
        lines.append('')

        # Relation declarations
        lines.append('// --- Relation declarations ---')
        for rel_name, sorts in self.relations.items():
            params = []
            for i, s in enumerate(sorts):
                params.append(f'v{i}: unsigned')
            decl = ', '.join(params)
            lines.append(f'.decl {rel_name}({decl})')
        lines.append('')

        # Rules and facts
        lines.append('// --- Rules and facts ---')
        for rule in self.rules:
            lines.append(rule)
        lines.append('')

        # Output directives
        lines.append('// --- Queries ---')
        for rel in self.outputs:
            lines.append(f'.output {rel}')

        return '\n'.join(lines) + '\n'


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    if len(sys.argv) < 2:
        print("Usage: python3 smt2_to_souffle.py <input.smt2> [output.dl]",
              file=sys.stderr)
        sys.exit(1)

    input_file = sys.argv[1]
    output_file = sys.argv[2] if len(sys.argv) > 2 else None

    with open(input_file) as f:
        text = f.read()

    exprs = parse_all(text)
    converter = SMT2ToSouffle()
    converter.process(exprs)
    output = converter.generate()

    if output_file:
        with open(output_file, 'w') as f:
            f.write(output)
        print(f"Generated {output_file}", file=sys.stderr)
    else:
        print(output)


if __name__ == '__main__':
    main()
